### ISSUE TITLE
De-static itp

### ISSUE THREAD

**Issue by kaolpr** [vanqyard/SZCZR#11]
Posprzątałem dość solidnie (na wzór tego co zaczął robić Amadeusz w module symulacji) w pasażerach i symulacji. Moduły te są już dość mocno dodokumentowane.

Uwaga! Jest błąd z którym zmagam się od pewnego czasu i mam pewną trudność z jego wyśledzeniem, a mianowicie w pliku SimulationEventHandler w funkcji process(WaitingPassengersEvent) występuję NullPointerException w momencie (jak sądzę) dojechania do przystanku.

Uwaga 2! Moduł Sync w trybie automatycznym nie czeka na zakończenie działania modułów (ModuleReadyEvent - tak, wiem, był CycleCompletedEvent, ale de facto się dublowały więc zrobiłem z nich jeden, nie zmienia to faktu, że ta wersja sync'a nie sprawdza czy moduły skończyły co miały skończyć).

Uwaga 3! GUI nie wyświetla danych z Mockup'ów... Dorobiłem toString() do wszystkich coby łatwo było sprawdzać co jest w środku. Moduł pasażerów wypisuje wszystko co jest w mockup'ie zaraz przed wysłaniem.

**Comment by vanqyard** [comment]
Podejrzewam, że może chodzić o połączenie przez sieć, bo moje testy
działają. Tak czy inaczej też trochę modyfikowałem GUI. W takim razie zadam
pytania:
1. Kiedy się spotykamy?
2. Kiedy oddajemy?
kalopr - jbc mam Twoją myszkę.

W dniu 6 stycznia 2015 15:40 użytkownik kaolpr <notifications@github.com>
napisał:

**Comment by amis92** [comment]
Dopiero wróciłem ze Szwajcarii:

1. Bardzo się cieszę że poszło tak do przodu.
2. Nie mam pojęcia jak myśmy się w końcu umówili.
3. Kiedy spotkanie/oddanie też nie wiem.
