### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by kaolpr** [vanqyard/SZCZR#12]
Chyba jednak coś jest nie do końca tak jak powinno... Albo nie ogarniam co to ma wyświetlać...

![zrzut ekranu z 2015-01-13 23 35 44](https://cloud.githubusercontent.com/assets/9166701/5730727/09116536-9b7d-11e4-8072-3f613946d325.png)

**Comment by vanqyard** [comment]
Czego brakuje? Czy chodzi Ci o to, ze w opisie status bara nie ma nazwy
przystanku na jakim sie ewentualnie znajduje autobus ?

2015-01-13 23:38 GMT+01:00 kaolpr <notifications@github.com>:

**Comment by vanqyard** [comment]
Ok, juz widze. Jesli chodzi o id=0 na kazdym progress bar nie wiem o co
biega, bo u mnie dzialalo, byc moze kwestia zlych danych testowych, zaraz
to sprawdze.

W dniu 13 stycznia 2015 23:44 użytkownik vanqyard . <vanqyard@gmail.com>
napisał:

**Comment by vanqyard** [comment]
Mogę zapytać gdzie jest test gui który odpalasz bo za cholerę nie mogę go
znaleźć

W dniu 13 stycznia 2015 23:49 użytkownik vanqyard . <vanqyard@gmail.com>
napisał:

**Comment by kaolpr** [comment]
burtis.modules.gui.GuiModule

2015-01-14 0:10 GMT+01:00 Rafał Braun <notifications@github.com>:

**Comment by vanqyard** [comment]
Ok, i jestes na 100% pewien ze ustawiasz id w kazdym MockupBus ? Bo moj
test dziala bez problemu i bierze właśnie dane z Mockupa w argumencie
refresh.

W dniu 14 stycznia 2015 00:24 użytkownik kaolpr <notifications@github.com>
napisał:

**Comment by kaolpr** [comment]
No raczej. Poza tym, że jest to w kodzie
(burtis.common.mockups.MockupBus.java:51) to jeszcze przed wysłaniem jest
wypisywany Mockup (w module Passenger) i tam też widoczne są id autobusów.

Spróbuj zrobić test na reszcie programu (czyli na tym co jest teraz w
master).

2015-01-14 0:38 GMT+01:00 Rafał Braun <notifications@github.com>:

> Ok, i jestes na 100% pewien ze ustawiasz id w kazdym MockupBus ? Bo moj
> test dziala bez problemu i bierze właśnie dane z Mockupa w argumencie
> refresh.
>
> W dniu 14 stycznia 2015 00:24 użytkownik kaolpr <notifications@github.com>
>
> napisał:
>
> > burtis.modules.gui.GuiModule
> >
> > 2015-01-14 0:10 GMT+01:00 Rafał Braun <notifications@github.com>:
> >
> > > Mogę zapytać gdzie jest test gui który odpalasz bo za cholerę nie mogę
> > go
> > > znaleźć
> > >
> > > W dniu 13 stycznia 2015 23:49 użytkownik vanqyard . <
> vanqyard@gmail.com>
> >
> > > napisał:
> > >
> > > > Ok, juz widze. Jesli chodzi o id=0 na kazdym progress bar nie wiem o
> > co
> > > > biega, bo u mnie dzialalo, byc moze kwestia zlych danych testowych,
> > > zaraz
> > > > to sprawdze.
> > > >
> > > > W dniu 13 stycznia 2015 23:44 użytkownik vanqyard . <
> > vanqyard@gmail.com>
> > >
> > > > napisał:
> > > >
> > > > Czego brakuje? Czy chodzi Ci o to, ze w opisie status bara nie ma
> > nazwy
> > > >> przystanku na jakim sie ewentualnie znajduje autobus ?
> > > >>
> > > >> 2015-01-13 23:38 GMT+01:00 kaolpr <notifications@github.com>:
> > > >>
> > > >>> Chyba jednak coś jest nie do końca tak jak powinno... Albo nie
> > > ogarniam
> > > >>> co to ma wyświetlać...
> > > >>>
> > > >>> [image: zrzut ekranu z 2015-01-13 23 35 44]
> > > >>> <
> > >
> >
> https://cloud.githubusercontent.com/assets/9166701/5730727/09116536-9b7d-11e4-8072-3f613946d325.png>
>
> >
> > >
> > > >>>
> > > >>> —
> > > >>> Reply to this email directly or view it on GitHub
> > > >>> <https://github.com/vanqyard/SZCZR/issues/12>.
> > > >>>
> > > >>
> > > >>
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69839962>.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69841762>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69843721>.
>



-- 
Pozdrawiam,
Mikołaj Sowiński

**Comment by vanqyard** [comment]
Podejrzewam, że chodzi o konstruktor MockupBus - Ty miałeś go z Integers,
zaś ja, ponieważ dodawałem dane w pętli, miałem go z inta. Sprawdź czy Ci
działa.

W dniu 14 stycznia 2015 01:01 użytkownik kaolpr <notifications@github.com>
napisał:

**Comment by kaolpr** [comment]
Ale ja nie korzystam z wersji z jawną deklaracją id, tylko z obiektem
autobusu. Z resztą, przecież dostajesz uzupełnionego Mockupa, są w nim
takie dane jak w symulacji (to co jest wypisywane przez PassengerModule
zaraz przed wysłaniem do GUI).

2015-01-14 1:24 GMT+01:00 Rafał Braun <notifications@github.com>:

> Podejrzewam, że chodzi o konstruktor MockupBus - Ty miałeś go z Integers,
> zaś ja, ponieważ dodawałem dane w pętli, miałem go z inta. Sprawdź czy Ci
> działa.
>
> W dniu 14 stycznia 2015 01:01 użytkownik kaolpr <notifications@github.com>
>
> napisał:
>
> > No raczej. Poza tym, że jest to w kodzie
> > (burtis.common.mockups.MockupBus.java:51) to jeszcze przed wysłaniem
> jest
> > wypisywany Mockup (w module Passenger) i tam też widoczne są id
> autobusów.
> >
> > Spróbuj zrobić test na reszcie programu (czyli na tym co jest teraz w
> > master).
> >
> > 2015-01-14 0:38 GMT+01:00 Rafał Braun <notifications@github.com>:
> >
> > > Ok, i jestes na 100% pewien ze ustawiasz id w kazdym MockupBus ? Bo
> moj
> > > test dziala bez problemu i bierze właśnie dane z Mockupa w argumencie
> > > refresh.
> > >
> > > W dniu 14 stycznia 2015 00:24 użytkownik kaolpr <
> > notifications@github.com>
> > >
> > > napisał:
> > >
> > > > burtis.modules.gui.GuiModule
> > > >
> > > > 2015-01-14 0:10 GMT+01:00 Rafał Braun <notifications@github.com>:
> > > >
> > > > > Mogę zapytać gdzie jest test gui który odpalasz bo za cholerę nie
> > mogę
> > > > go
> > > > > znaleźć
> > > > >
> > > > > W dniu 13 stycznia 2015 23:49 użytkownik vanqyard . <
> > > vanqyard@gmail.com>
> > > >
> > > > > napisał:
> > > > >
> > > > > > Ok, juz widze. Jesli chodzi o id=0 na kazdym progress bar nie
> wiem
> > o
> > > > co
> > > > > > biega, bo u mnie dzialalo, byc moze kwestia zlych danych
> > testowych,
> > > > > zaraz
> > > > > > to sprawdze.
> > > > > >
> > > > > > W dniu 13 stycznia 2015 23:44 użytkownik vanqyard . <
> > > > vanqyard@gmail.com>
> > > > >
> > > > > > napisał:
> > > > > >
> > > > > > Czego brakuje? Czy chodzi Ci o to, ze w opisie status bara nie
> ma
> > > > nazwy
> > > > > >> przystanku na jakim sie ewentualnie znajduje autobus ?
> > > > > >>
> > > > > >> 2015-01-13 23:38 GMT+01:00 kaolpr <notifications@github.com>:
> > > > > >>
> > > > > >>> Chyba jednak coś jest nie do końca tak jak powinno... Albo nie
> > > > > ogarniam
> > > > > >>> co to ma wyświetlać...
> > > > > >>>
> > > > > >>> [image: zrzut ekranu z 2015-01-13 23 35 44]
> > > > > >>> <
> > > > >
> > > >
> > >
> >
> https://cloud.githubusercontent.com/assets/9166701/5730727/09116536-9b7d-11e4-8072-3f613946d325.png>
>
> >
> > >
> > > >
> > > > >
> > > > > >>>
> > > > > >>> —
> > > > > >>> Reply to this email directly or view it on GitHub
> > > > > >>> <https://github.com/vanqyard/SZCZR/issues/12>.
> > > > > >>>
> > > > > >>
> > > > > >>
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69839962>.
>
> >
> > > > >
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69841762>.
>
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69843721>.
> > >
> >
> >
> >
> > --
> > Pozdrawiam,
> > Mikołaj Sowiński
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69846415>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69848617>.
>



-- 
Pozdrawiam,
Mikołaj Sowiński

**Comment by vanqyard** [comment]
No dobra, ale nie dziala Ci tylko Id czy passengerList też tam nie ma?

W dniu 14 stycznia 2015 01:30 użytkownik kaolpr <notifications@github.com>
napisał:

**Comment by kaolpr** [comment]
Przede wszystkim mniej więcej w 8 iteracji mam na liście same autobusy o id
0 z różniastymi postępami

2015-01-14 1:33 GMT+01:00 Rafał Braun <notifications@github.com>:

> No dobra, ale nie dziala Ci tylko Id czy passengerList też tam nie ma?
>
> W dniu 14 stycznia 2015 01:30 użytkownik kaolpr <notifications@github.com>
>
> napisał:
>
> > Ale ja nie korzystam z wersji z jawną deklaracją id, tylko z obiektem
> > autobusu. Z resztą, przecież dostajesz uzupełnionego Mockupa, są w nim
> > takie dane jak w symulacji (to co jest wypisywane przez PassengerModule
> > zaraz przed wysłaniem do GUI).
> >
> > 2015-01-14 1:24 GMT+01:00 Rafał Braun <notifications@github.com>:
> >
> > > Podejrzewam, że chodzi o konstruktor MockupBus - Ty miałeś go z
> > Integers,
> > > zaś ja, ponieważ dodawałem dane w pętli, miałem go z inta. Sprawdź czy
> > Ci
> > > działa.
> > >
> > > W dniu 14 stycznia 2015 01:01 użytkownik kaolpr <
> > notifications@github.com>
> > >
> > > napisał:
> > >
> > > > No raczej. Poza tym, że jest to w kodzie
> > > > (burtis.common.mockups.MockupBus.java:51) to jeszcze przed wysłaniem
> > > jest
> > > > wypisywany Mockup (w module Passenger) i tam też widoczne są id
> > > autobusów.
> > > >
> > > > Spróbuj zrobić test na reszcie programu (czyli na tym co jest teraz
> w
> > > > master).
> > > >
> > > > 2015-01-14 0:38 GMT+01:00 Rafał Braun <notifications@github.com>:
> > > >
> > > > > Ok, i jestes na 100% pewien ze ustawiasz id w kazdym MockupBus ?
> Bo
> > > moj
> > > > > test dziala bez problemu i bierze właśnie dane z Mockupa w
> > argumencie
> > > > > refresh.
> > > > >
> > > > > W dniu 14 stycznia 2015 00:24 użytkownik kaolpr <
> > > > notifications@github.com>
> > > > >
> > > > > napisał:
> > > > >
> > > > > > burtis.modules.gui.GuiModule
> > > > > >
> > > > > > 2015-01-14 0:10 GMT+01:00 Rafał Braun <notifications@github.com>:
>
> > > > > >
> > > > > > > Mogę zapytać gdzie jest test gui który odpalasz bo za cholerę
> > nie
> > > > mogę
> > > > > > go
> > > > > > > znaleźć
> > > > > > >
> > > > > > > W dniu 13 stycznia 2015 23:49 użytkownik vanqyard . <
> > > > > vanqyard@gmail.com>
> > > > > >
> > > > > > > napisał:
> > > > > > >
> > > > > > > > Ok, juz widze. Jesli chodzi o id=0 na kazdym progress bar
> nie
> > > wiem
> > > > o
> > > > > > co
> > > > > > > > biega, bo u mnie dzialalo, byc moze kwestia zlych danych
> > > > testowych,
> > > > > > > zaraz
> > > > > > > > to sprawdze.
> > > > > > > >
> > > > > > > > W dniu 13 stycznia 2015 23:44 użytkownik vanqyard . <
> > > > > > vanqyard@gmail.com>
> > > > > > >
> > > > > > > > napisał:
> > > > > > > >
> > > > > > > > Czego brakuje? Czy chodzi Ci o to, ze w opisie status bara
> nie
> > > ma
> > > > > > nazwy
> > > > > > > >> przystanku na jakim sie ewentualnie znajduje autobus ?
> > > > > > > >>
> > > > > > > >> 2015-01-13 23:38 GMT+01:00 kaolpr <notifications@github.com>:
>
> >
> > > > > > > >>
> > > > > > > >>> Chyba jednak coś jest nie do końca tak jak powinno... Albo
> > nie
> > > > > > > ogarniam
> > > > > > > >>> co to ma wyświetlać...
> > > > > > > >>>
> > > > > > > >>> [image: zrzut ekranu z 2015-01-13 23 35 44]
> > > > > > > >>> <
> > > > > > >
> > > > > >
> > > > >
> > > >
> > >
> >
> https://cloud.githubusercontent.com/assets/9166701/5730727/09116536-9b7d-11e4-8072-3f613946d325.png>
>
> >
> > >
> > > >
> > > > >
> > > > > >
> > > > > > >
> > > > > > > >>>
> > > > > > > >>> —
> > > > > > > >>> Reply to this email directly or view it on GitHub
> > > > > > > >>> <https://github.com/vanqyard/SZCZR/issues/12>.
> > > > > > > >>>
> > > > > > > >>
> > > > > > > >>
> > > > > > > >
> > > > > > >
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > <
> > https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69839962>.
> > >
> > > >
> > > > > > >
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69841762>.
> >
> > >
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69843721>.
>
> >
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Pozdrawiam,
> > > > Mikołaj Sowiński
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69846415>.
>
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69848617>.
> > >
> >
> >
> >
> > --
> > Pozdrawiam,
> > Mikołaj Sowiński
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69849247>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69849529>.
>



-- 
Pozdrawiam,
Mikołaj Sowiński

**Comment by vanqyard** [comment]
Czyli, żebym dobrze zrozumiał, gui zawiera złe dane od początku czy od
pewnej iteracji ?

W dniu 14 stycznia 2015 01:38 użytkownik kaolpr <notifications@github.com>
napisał:

**Comment by kaolpr** [comment]
Dokładnie od 2. W pierwszej jest ok.

2015-01-14 1:45 GMT+01:00 Rafał Braun <notifications@github.com>:

> Czyli, żebym dobrze zrozumiał, gui zawiera złe dane od początku czy od
> pewnej iteracji ?
>
> W dniu 14 stycznia 2015 01:38 użytkownik kaolpr <notifications@github.com>
>
> napisał:
>
> > Przede wszystkim mniej więcej w 8 iteracji mam na liście same autobusy o
> > id
> > 0 z różniastymi postępami
> >
> > 2015-01-14 1:33 GMT+01:00 Rafał Braun <notifications@github.com>:
> >
> > > No dobra, ale nie dziala Ci tylko Id czy passengerList też tam nie ma?
> > >
> > > W dniu 14 stycznia 2015 01:30 użytkownik kaolpr <
> > notifications@github.com>
> > >
> > > napisał:
> > >
> > > > Ale ja nie korzystam z wersji z jawną deklaracją id, tylko z
> obiektem
> > > > autobusu. Z resztą, przecież dostajesz uzupełnionego Mockupa, są w
> nim
> > > > takie dane jak w symulacji (to co jest wypisywane przez
> > PassengerModule
> > > > zaraz przed wysłaniem do GUI).
> > > >
> > > > 2015-01-14 1:24 GMT+01:00 Rafał Braun <notifications@github.com>:
> > > >
> > > > > Podejrzewam, że chodzi o konstruktor MockupBus - Ty miałeś go z
> > > > Integers,
> > > > > zaś ja, ponieważ dodawałem dane w pętli, miałem go z inta. Sprawdź
> > czy
> > > > Ci
> > > > > działa.
> > > > >
> > > > > W dniu 14 stycznia 2015 01:01 użytkownik kaolpr <
> > > > notifications@github.com>
> > > > >
> > > > > napisał:
> > > > >
> > > > > > No raczej. Poza tym, że jest to w kodzie
> > > > > > (burtis.common.mockups.MockupBus.java:51) to jeszcze przed
> > wysłaniem
> > > > > jest
> > > > > > wypisywany Mockup (w module Passenger) i tam też widoczne są id
> > > > > autobusów.
> > > > > >
> > > > > > Spróbuj zrobić test na reszcie programu (czyli na tym co jest
> > teraz
> > > w
> > > > > > master).
> > > > > >
> > > > > > 2015-01-14 0:38 GMT+01:00 Rafał Braun <notifications@github.com>:
>
> > > > > >
> > > > > > > Ok, i jestes na 100% pewien ze ustawiasz id w kazdym MockupBus
> ?
> > > Bo
> > > > > moj
> > > > > > > test dziala bez problemu i bierze właśnie dane z Mockupa w
> > > > argumencie
> > > > > > > refresh.
> > > > > > >
> > > > > > > W dniu 14 stycznia 2015 00:24 użytkownik kaolpr <
> > > > > > notifications@github.com>
> > > > > > >
> > > > > > > napisał:
> > > > > > >
> > > > > > > > burtis.modules.gui.GuiModule
> > > > > > > >
> > > > > > > > 2015-01-14 0:10 GMT+01:00 Rafał Braun <
> > notifications@github.com>:
> > >
> > > > > > > >
> > > > > > > > > Mogę zapytać gdzie jest test gui który odpalasz bo za
> > cholerę
> > > > nie
> > > > > > mogę
> > > > > > > > go
> > > > > > > > > znaleźć
> > > > > > > > >
> > > > > > > > > W dniu 13 stycznia 2015 23:49 użytkownik vanqyard . <
> > > > > > > vanqyard@gmail.com>
> > > > > > > >
> > > > > > > > > napisał:
> > > > > > > > >
> > > > > > > > > > Ok, juz widze. Jesli chodzi o id=0 na kazdym progress
> bar
> > > nie
> > > > > wiem
> > > > > > o
> > > > > > > > co
> > > > > > > > > > biega, bo u mnie dzialalo, byc moze kwestia zlych danych
> > > > > > testowych,
> > > > > > > > > zaraz
> > > > > > > > > > to sprawdze.
> > > > > > > > > >
> > > > > > > > > > W dniu 13 stycznia 2015 23:44 użytkownik vanqyard . <
> > > > > > > > vanqyard@gmail.com>
> > > > > > > > >
> > > > > > > > > > napisał:
> > > > > > > > > >
> > > > > > > > > > Czego brakuje? Czy chodzi Ci o to, ze w opisie status
> bara
> > > nie
> > > > > ma
> > > > > > > > nazwy
> > > > > > > > > >> przystanku na jakim sie ewentualnie znajduje autobus ?
> > > > > > > > > >>
> > > > > > > > > >> 2015-01-13 23:38 GMT+01:00 kaolpr <
> > notifications@github.com>:
> > >
> > > >
> > > > > > > > > >>
> > > > > > > > > >>> Chyba jednak coś jest nie do końca tak jak powinno...
> > Albo
> > > > nie
> > > > > > > > > ogarniam
> > > > > > > > > >>> co to ma wyświetlać...
> > > > > > > > > >>>
> > > > > > > > > >>> [image: zrzut ekranu z 2015-01-13 23 35 44]
> > > > > > > > > >>> <
> > > > > > > > >
> > > > > > > >
> > > > > > >
> > > > > >
> > > > >
> > > >
> > >
> >
> https://cloud.githubusercontent.com/assets/9166701/5730727/09116536-9b7d-11e4-8072-3f613946d325.png>
>
> >
> > >
> > > >
> > > > >
> > > > > >
> > > > > > >
> > > > > > > >
> > > > > > > > >
> > > > > > > > > >>>
> > > > > > > > > >>> —
> > > > > > > > > >>> Reply to this email directly or view it on GitHub
> > > > > > > > > >>> <https://github.com/vanqyard/SZCZR/issues/12>.
> > > > > > > > > >>>
> > > > > > > > > >>
> > > > > > > > > >>
> > > > > > > > > >
> > > > > > > > >
> > > > > > > > > —
> > > > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > > > <
> > > > https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69839962>.
> > > > >
> > > > > >
> > > > > > > > >
> > > > > > > >
> > > > > > > > —
> > > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > > <
> > > https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69841762>.
> > > >
> > > > >
> > > > > > > >
> > > > > > >
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > <
> > https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69843721>.
> > >
> > > >
> > > > > > >
> > > > > >
> > > > > >
> > > > > >
> > > > > > --
> > > > > > Pozdrawiam,
> > > > > > Mikołaj Sowiński
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69846415>.
> >
> > >
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69848617>.
>
> >
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Pozdrawiam,
> > > > Mikołaj Sowiński
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69849247>.
>
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69849529>.
> > >
> >
> >
> >
> > --
> > Pozdrawiam,
> > Mikołaj Sowiński
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69849948>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vanqyard/SZCZR/issues/12#issuecomment-69850651>.
>



-- 
Pozdrawiam,
Mikołaj Sowiński

**Comment by vanqyard** [comment]
Ok, juz chyba wiem o co chodzi. Zaraz to naprawię.

W dniu 14 stycznia 2015 01:50 użytkownik kaolpr <notifications@github.com>
napisał:

**Comment by vanqyard** [comment]
Ok, powinno działać.

W dniu 14 stycznia 2015 01:56 użytkownik vanqyard . <vanqyard@gmail.com>
napisał:

**Comment by vanqyard** [comment]
I jak, dziala ?

W dniu 14 stycznia 2015 02:01 użytkownik vanqyard . <vanqyard@gmail.com>
napisał:

**Comment by amis92** [comment]
@vanqyard chyba ten null pointery przy connect eventach dostawałeś w teście bo nie miasz tam modułu sieciowego zainicjalizowanego

Uporządkowałem kilka rzeczy, za moment jeszcze dodam dodawanie pasażerów. Powinno być generalnie ok. A ten genTime min/max to jest czas generacji czego?

**Comment by amis92** [comment]
bo ```package burtis.common.events.Passengers.PassengerGenerationRateConfigurationEvent``` ustawia długość cyklu i ilość pasażerów na cykl.

**Comment by vanqyard** [comment]
Min i Max czas generacji nowego pasazera

2015-01-14 9:23 GMT+01:00 Amadeusz Sadowski <notifications@github.com>:
