### ISSUE TITLE
Testy

### ISSUE THREAD

**Issue by amis92** [vanqyard/SZCZR#13]
Aby utworzyć w Eclipse burtis.jar, kilkasz dwukrotnie burtis-jar.jardesc (w eclipse), to plik w głównym katalogu projektu. Klikasz Finish i eksportuje co trzeba. Wchodzisz do głównego katalogu w eksporatorze i klikasz dwukrotnie burtis.bat (windows) albo burtis.sh (linux). Powinno poodpalać wszystkie moduły, razem z GUI.

Potestujcie, bo autobusy się zatrzymują w połowie progresu, dane o pasażerach się powtarzają albo nie odświeżają i trochę mi się już nie chce dochodzić co gdzie nie działa. Ważne że obecnie symulacja działa w kwestii że sie nie wywala bez potrzeby, eventy chodzą i dochodzą, zegar i synchronizacja też działa i generalnie teraz dobrze by było doszlifować co się dzieje i jak z busami i pasażerami, być może to kwestia GUI, może nie.

**Comment by amis92** [comment]
@vanqyard @kaolpr plz

**Comment by amis92** [comment]
A, @kaolpr , z jakiegoś powodu Symulacja nie obsługuje już BusStopsListRequestEvent, a było to potrzebne BusSchedulerowi

**Comment by kaolpr** [comment]
Zmieniłem w BusSchedulerze, nie wiedziałem że z tego korzysta. Teraz wszystkie przystanki są ciągnięte z domyślnej konfiguracji.

**Comment by amis92** [comment]
Bardzo fajnie :) dzięki. Ja dzisiaj zupgradowałem panel pasażerów.

Są problemy:
1. Pasażerowie nie wsiadają do autobusów.
2. Autobusy zatrzymują się na progresie 30, za wyjątkiem pierwszego który dojeżdża do 60. Status podają BUSSTOP, i że na Placu Zamkowym. Coś jest nie halo z DEPOTem chyba.

**Comment by kaolpr** [comment]
Raczej z transakcjami. Właśnie nad tym pracuję.

2015-01-15 23:44 GMT+01:00 Amadeusz Sadowski <notifications@github.com>:

> Bardzo fajnie :) dzięki. Ja dzisiaj zupgradowałem panel pasażerów.
>
> Są problemy:
> 1. Pasażerowie nie wsiadają do autobusów.
> 2. Autobusy zatrzymują się na progresie 30, za wyjątkiem pierwszego który
> dojeżdża do 60. Status podają BUSSTOP, i że na Placu Zamkowym. Coś jest nie
> halo z DEPOTem chyba.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vanqyard/SZCZR/issues/13#issuecomment-70176990>.
>



-- 
Pozdrawiam,
Mikołaj Sowiński
