### ISSUE TITLE
Ostatnie bugi

### ISSUE THREAD

**Issue by amis92** [vanqyard/SZCZR#15]
Sorry, musiałem wprowadzić gdzieś błąd w GUI z tą bajer-listą ze skreślaniem etc.

Bugi:
- Jest 30 pasażerów, 1 wysiada, 1 wsiada - 31 wierszy tabeli potrzebne, jest tylko 30 - outofboundsexception po twarzy.

Poza tym tak jakby w ogóle nie ma znaczenia to co wysyła BusScheduler ?

Pasażerowie na pętli nie mają okazji wysiąść (na ostatnim przystanku).

Chyba wszystko póki co.

**Comment by kaolpr** [comment]
Poza GUI poprawione.

2015-01-21 7:37 GMT+01:00 Amadeusz Sadowski <notifications@github.com>:

> Sorry, musiałem wprowadzić gdzieś błąd w GUI z tą bajer-listą ze
> skreślaniem etc.
>
> Bugi:
>
>    - Jest 30 pasażerów, 1 wysiada, 1 wsiada - 31 wierszy tabeli
>    potrzebne, jest tylko 30 - outofboundsexception po twarzy.
>
> Poza tym tak jakby w ogóle nie ma znaczenia to co wysyła BusScheduler ?
>
> Pasażerowie na pętli nie mają okazji wysiąść (na ostatnim przystanku).
>
> Chyba wszystko póki co.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vanqyard/SZCZR/issues/15>.
>



-- 
Pozdrawiam,
Mikołaj Sowiński

**Comment by amis92** [comment]
Rany dzięki wielkie. GUI to dam radę bo po prostu najwyżej wszystkie ograniczenia posprawdzam w pętli, ale busów bym nie poprawił. Napiszę co powie jak oddamy. :)

Pozdrawiam,
Amadeusz Sadowski

wysłane z Lumii 820

-----Original Message-----
